### ISSUE TITLE
could the rg command have a preview?

### ISSUE THREAD

**Issue by alok** [vijaymarupudi/nvim-fzf-commands#2]
it's pretty handy otherwise

**Comment by vijaymarupudi** [comment]
Ask, and you shall receive

![](https://raw.githubusercontent.com/vijaymarupudi/nvim-fzf-commands/master/gifs/rg.gif)

**Comment by alok** [comment]
Thanks! Now I just have to figure out how to make this a fully interactive searcher

**Comment by vijaymarupudi** [comment]
I'm curious what you mean by "fully interactive"
