### ISSUE TITLE
Respect $FZF_* environment variables?

### ISSUE THREAD

**Issue by ahmedelgabri** [vijaymarupudi/nvim-fzf-commands#3]
Right now commands are a bit more opinionated with hardcoded tools etc… (`fd`, `find`,…) maybe it's better to check if `$FZF_*`(_specifically `FZF_DEFAULT_COMMAND` & `FZF_PREVIEW_COMMAND`_) variables are set first & then fallback to specific tools or configs, etc…

**Comment by vijaymarupudi** [comment]
I leaning against this, because people who have it set, have it set for shell usage, and I think neovim usage is a different thing. 

The hardcoding I think is pretty conservative, most people who have `fd` or `bat` installed, often have them installed because they are user interface improvements.

If there's a configuration option I can add to help your use case, I can look into it, if you can describe it to me.

**Comment by ahmedelgabri** [comment]
> I leaning against this, because people who have it set, have it set for shell usage, and I think neovim usage is a different thing.
>
> The hardcoding I think is pretty conservative, most people who have `fd` or `bat` installed, often have them installed because they are user interface improvements.

There are lots of assumptions here I'm afraid, 

1. I do have the setup of my FZF for both shell & neovim fully controlled from `$FZF_*` variables. Because I want things to be consistent. When I want something custom I create a custom shell script to handle that exception & add it to my `$PATH`

2. not everyone will use the same tools. (I do have both BTW) but that doesn't mean that everyone will have both. Even me having both I still have different settings for them than the ones used in the commands by default. 

I think it's a better experience to use `$FZF_DEFAULT_COMMAND` + `$FZF_PREVIEW_COMMAND` by default & provide a way to override them if needed inside the script. Something like this for example.

```lua
require("fzf-commands").files({ 
  cmd = "fd",
  preview_cmd = "cat"
})
```

This means that out of the box it will work with users as they expect `fzf` to work but if they want to override commands or change them they still can.

**Comment by vijaymarupudi** [comment]
I think this is a difference of design taste, one's `$FZF_DEFAULT_COMMAND` isn't required to be about files, it may as well be one's git commits or anything else. I don't want that interfering with this plugin working outside the box.

This repository is meant to be opinionated, both for reducing maintenance burden and to reduce configuration, but that shouldn't stop you from using the `nvim-fzf` library, which is meant to work for everyone.

This snippet accomplishes most of everything you want, I think.

```lua
local fzf = require("fzf").fzf

coroutine.wrap(function ()
  -- nvim-fzf respects env variables, so you should get the preview by default
   local choices = fzf("$FZF_DEFAULT_COMMAND") 
   if choices then
      vim.cmd("e " .. vim.fn.fnameescape(choices[1]))
   end
end)()
```
