### ISSUE TITLE
Incompatible with Fish shell.

### ISSUE THREAD

**Issue by milkypostman** [vijaymarupudi/nvim-fzf-commands#4]
Unfortunately when using the `files` command with `bat` installed, the command doesn't work because of the preview argument. The problem is just that Fish doesn't support the standard bash/zsh substitutions. I guess because it's non-POSIX compatible. 

```
fish: Command substitutions not allowed
($FZF_PREVIEW_LINES - 5)
^
in command substitution
fish: Unknown error while evaluating command substitution
bat --line-range=:$(($FZF_PREVIEW_LINES - 5)) --color always -- 'src/exitwp/README.rst
```

I'm not sure the right way to fix this. You could run the commands under bash, or just not try to do math with `FZF_PREVIEW_LINES`. 

In Fish there is a builtin `math` command, and you would do something like,

```
bat --line-range=:(math $FZF_PREVIEW_LINES - 5) --color always -- 'src/exitwp/README.rst'
```

Anyways, not looking for a fix. But just a heads up.

**Comment by vijaymarupudi** [comment]
I consider this a bug that needs to be fixed, thank you for reporting.

I just pushed https://github.com/vijaymarupudi/nvim-fzf-commands/commit/c6188c8618ca6b579af37cbc242414e1016bcd45 to master, can you check if that fixes the issue?

**Comment by milkypostman** [comment]
Works!

**Comment by vijaymarupudi** [comment]
Great, thank you!
