### ISSUE TITLE
files() fails on files containing spaces

### ISSUE THREAD

**Issue by mrkline** [vijaymarupudi/nvim-fzf-commands#5]
`files()` fails to provide the full file name to bat, stopping at the first space and printing
```
 [bat error]: './<part>': No such file or directory (os error 2)
```

![image](https://user-images.githubusercontent.com/493463/160990067-19b06857-d35c-412c-a9ea-76e24aedf2a7.png)

Interestingly reverting c6188c8618ca6b579af37cbc242414e1016bcd45 seems to fix the problem.

zsh is my default shell, for what it's worth.

**Comment by vijaymarupudi** [comment]
Looks like it was a double quoting error, please test now and let me know if it works!
