### ISSUE TITLE
Is it possible to set FZF_DEFAULT_COMMAND?

### ISSUE THREAD

**Issue by bugb** [vijaymarupudi/nvim-fzf-commands#7]
By default, using `fd` for searching file, it cant show hidden files (those start with `.`).

Is it possible to add flag for `fd` that is currently used by `fzf`?

Example:

```vimscript
let $FZF_DEFAULT_COMMAND='fd -uu'
```

**Comment by vijaymarupudi** [comment]
I added the options `command_flags` for the `files` command. That should allow you to customize the flags passed to `fd`.

**Comment by bugb** [comment]
Thank you so much for your super quick commit!
